<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>bcc22d4f-eb7c-4b91-9388-8f41b8ef786e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div/div[9]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33ecb0c3-b884-49c6-b1ed-3664b6c0084d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/dashboard/health-file.svg</value>
      <webElementGuid>2da5bf7d-6cbc-4200-9571-5461239e1044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;user-dashboard md:tw-mt-0 tw-mt-7&quot;]/div[@class=&quot;md:tw-mb-10 feature-category-list md:tw-mt-5&quot;]/div[@class=&quot;ant-row feature-category-menu&quot;]/div[@class=&quot;ant-col ant-col-xs-8 ant-col-sm-6 ant-col-lg-4&quot;]/div[@class=&quot;feature-category-menu-item tw-relative md:hover:tw-shadow-[0_3px_14px_0_rgba(0,0,0,0.25)] md:hover:tw-rounded-2xl tw-transition tw-duration-300 hover:tw-transition-all hover:after:tw-content-[''] hover:after:tw-absolute hover:after:tw-bottom-0 hover:after:tw-h-1 hover:after:tw-left-0 hover:after:tw-right-0 hover:after:tw-m-auto hover:after:tw-w-3/12 hover:after:tw-bg-[#31C8C1] hover:after:tw-rounded-full&quot;]/a[1]/img[1]</value>
      <webElementGuid>85c8a72f-86b3-4543-8803-002ae361b847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div[9]/div/a/img</value>
      <webElementGuid>e9ac3bf5-e90c-41a5-948f-7d49d0ca4209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/dashboard/health-file.svg')]</value>
      <webElementGuid>3772aca7-4011-4ba6-9150-a8fd0bb2bf91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a/img</value>
      <webElementGuid>1f041b87-1400-4eb8-9f19-a133302bc13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/dashboard/health-file.svg']</value>
      <webElementGuid>799948ba-1071-4d0a-a2ac-73aa7086e6d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
