<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Wellnesscorner</name>
   <tag></tag>
   <elementGuidId>3970df21-9db5-4009-a051-b4543fc3ec3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3fc12d2c-ac4b-4eac-b9cd-7ab10833b577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg</value>
      <webElementGuid>4f5b94a0-b289-406f-a78f-fb0deddfb87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;redirect-to-app-page template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;logo-header&quot;]/a[1]/img[1]</value>
      <webElementGuid>de8e84c8-32c3-4a0a-9a0d-767f60958d11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/a/img</value>
      <webElementGuid>fef5bf7a-0659-43a8-85b1-a80a76c2c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg')]</value>
      <webElementGuid>e8c17e4c-20f1-42c7-b172-2a170cf87f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c3b9de94-557c-4c49-8d16-7ff7486756dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg']</value>
      <webElementGuid>cb7561b1-87ea-4f2b-ad7a-835a7a4ea65e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
