<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TheWellnessCorner_Text_Tab</name>
   <tag></tag>
   <elementGuidId>5e00474e-fb44-4823-80e2-2809c2bd5e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,&quot;https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
