<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop_div_concat(6, , 9, ,  Feet)_ant-slider-handle ant-tooltip-open</name>
   <tag></tag>
   <elementGuidId>28a9832f-85d1-4ce8-99b3-bba622d6215b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-slider-handle.ant-tooltip-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5881c3e-0011-47de-a64b-aee3dff9de4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-slider-handle ant-tooltip-open</value>
      <webElementGuid>3de363c5-eb74-4612-aa97-3806aab2116f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98e17b07-7f3e-4b21-9455-2180922de3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>375abd70-4e04-41a3-b7ad-0d5fc9b91b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>43af455f-84fb-4348-85ef-06293df03d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>220</value>
      <webElementGuid>b97e1f05-381e-4520-9abd-bb93c7b5e00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>207</value>
      <webElementGuid>fbde5be0-66af-45d8-b328-37f2b5ac6d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b80e254-85d2-4b24-b875-080cd9a164c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sm:tw-w-4/5 tw-w-full tw-m-auto tw-mb-12&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-12&quot;]/div[@class=&quot;tw-rounded-3xl tw-shadow-[0_2px_10px_#00000025] tw-bg-white md:tw-p-10 tw-px-6 tw-py-10&quot;]/div[@class=&quot;bmi-screen1&quot;]/div[@class=&quot;tw-mb-12&quot;]/div[@class=&quot;measure-wrapper tw-text-center tw-flex tw-justify-center tw-items-center tw-grid-flow-col&quot;]/div[@class=&quot;ant-row tw-w-full&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-slider ant-slider-horizontal&quot;]/div[@class=&quot;ant-slider-handle ant-tooltip-open&quot;]</value>
      <webElementGuid>8c77ca2b-157f-45c8-af1d-103ebd8aedd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>cbc3a3d0-9906-4cce-8538-c0a3b30cdae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>e4c94b38-4998-4099-ab45-80b2c7b4ad14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
