<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>76db8f19-80d2-47d3-943d-f47d26fd5df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.login-btn.btn.primary-gradient.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2669c985-d47e-4b44-b20d-cc00fd9f6aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8ec7badb-adbc-4d4f-8d21-df7bd8bc8f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-btn btn primary-gradient btn btn-primary</value>
      <webElementGuid>1b1b1e1d-87f3-49d6-991f-172d000d4b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>49383f16-6154-4a9d-ad65-ae8e5d2b0f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-panel tw-pb-5&quot;]/div[@class=&quot;login-form tw-mb-2&quot;]/form[1]/div[@class=&quot;form-group&quot;]/button[@class=&quot;login-btn btn primary-gradient btn btn-primary&quot;]</value>
      <webElementGuid>fb580296-c077-44a0-b1e1-9b57b2d907fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>9db50459-39d9-4581-bfb0-948d0e755ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/form/div[2]/button</value>
      <webElementGuid>0067df03-2e29-462f-a83b-cb69fbb474fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter email to get started!'])[1]/following::button[1]</value>
      <webElementGuid>e1bbcf63-510a-4a78-bb42-ea0f2912b4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/preceding::button[1]</value>
      <webElementGuid>45123b76-ffc9-41a3-86ee-4ed207227954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with Facebook'])[1]/preceding::button[1]</value>
      <webElementGuid>71184376-4741-4b0e-90b1-535fa884d4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>caa65e36-6146-45f6-b423-be0b020531d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>07a0dcee-c967-4ad2-9ec5-97e211f9f3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>6f1605c1-fa56-433b-bd13-0a019c57f938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
