<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_Password</name>
   <tag></tag>
   <elementGuidId>7b66128d-49fb-45f5-9aa7-1774642eab63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da755d25-0cd9-4a66-9aa3-aa3d407b562c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ac0247a0-8320-42fc-8e66-c40f943b0336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>d9c7df35-9979-4eb4-913e-b0001447eb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>13775ba4-047c-4197-bcb0-8725e53bdf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill roundedFormControl form-control</value>
      <webElementGuid>d48beb8f-a645-4573-aec6-7472ae07c04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>a3631580-a9f2-4991-a107-babc96e2c3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-panel tw-pb-5&quot;]/div[@class=&quot;login-form&quot;]/form[1]/div[@class=&quot;row-inner row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-password&quot;]/input[@class=&quot;fill roundedFormControl form-control&quot;]</value>
      <webElementGuid>cd9ddbbe-77ea-4588-8e59-aeb88bcf7139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Password']</value>
      <webElementGuid>d3b9d0fe-e693-44cd-ad31-1077e73b1990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/form/div/div/div/input</value>
      <webElementGuid>65b746dc-f9a8-40d6-88e1-b8b4077f217e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>244729db-c5bc-4f65-8cc1-02f8513ce0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Password' and @placeholder = 'Enter your password' and @type = 'password']</value>
      <webElementGuid>76c105ef-e6ab-450f-9d4e-7169e8199fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
