<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Health  Checks</name>
   <tag></tag>
   <elementGuidId>7700f123-b79e-4629-a3d1-058af18f1ba6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Health  Checks' or . = 'Health  Checks')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c769c50-fcca-48f3-991c-26ae0a9fe021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Health  Checks</value>
      <webElementGuid>89dc46ef-c88b-43f3-986e-48f59edabd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;user-dashboard md:tw-mt-0 tw-mt-7&quot;]/div[@class=&quot;md:tw-mb-10 feature-category-list md:tw-mt-5&quot;]/div[@class=&quot;ant-row feature-category-menu&quot;]/div[@class=&quot;ant-col ant-col-xs-8 ant-col-sm-6 ant-col-lg-4&quot;]/div[@class=&quot;feature-category-menu-item tw-relative md:hover:tw-shadow-[0_3px_14px_0_rgba(0,0,0,0.25)] md:hover:tw-rounded-2xl tw-transition tw-duration-300 hover:tw-transition-all hover:after:tw-content-[''] hover:after:tw-absolute hover:after:tw-bottom-0 hover:after:tw-h-1 hover:after:tw-left-0 hover:after:tw-right-0 hover:after:tw-m-auto hover:after:tw-w-3/12 hover:after:tw-bg-[#31C8C1] hover:after:tw-rounded-full&quot;]/a[1]</value>
      <webElementGuid>28fed0a6-c3d5-4307-9a5b-a8c7acd9f843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>2f6ef830-9df0-4c09-ab91-c86d5ebe470b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::a[1]</value>
      <webElementGuid>0287be77-30c6-4c86-a8c8-7c2e18771923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>19da469c-a75d-40c2-a8d2-4b7c0018d823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Health  Checks' or . = 'Health  Checks')]</value>
      <webElementGuid>2413af7f-79d0-47be-97d4-8582989dd8b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
